-- INSERT INTO charge(CHARGE_ID,CHARGE_NAME,CHARGE_ADDR,CHARGE_TYPE,BUSI_NAME) VALUES('1001','신교공영주차장','서울특별시 종로구 자하문로 89 (지하 2층 주차장)','2','에스트래픽');
-- INSERT INTO charge(CHARGE_ID,CHARGE_NAME,CHARGE_ADDR,CHARGE_TYPE,BUSI_NAME) VALUES('1002','신교공영주차장','서울특별시 종로구 자하문로 89 (지하 2층 주차장)','2','에스트래픽');
-- INSERT INTO charge(CHARGE_ID,CHARGE_NAME,CHARGE_ADDR,CHARGE_TYPE,BUSI_NAME) VALUES('1003','청와대 사랑채 주차장','서울특별시 종로구 효자로 67','4','서울에너지공사');
-- INSERT INTO charge(CHARGE_ID,CHARGE_NAME,CHARGE_ADDR,CHARGE_TYPE,BUSI_NAME) VALUES('1004','한국생산성본부','서울특별시 종로구 새문안로5가길 32 (지하4층 주차장)','2','타디스테크놀로지');
-- INSERT INTO charge(CHARGE_ID,CHARGE_NAME,CHARGE_ADDR,CHARGE_TYPE,BUSI_NAME) VALUES('1005','적선동 공영주차장','서울특별시 종로구 새문안로5길 49-1 (서울특별시 종로구 적선동 172 적선동공영주차장)','4','서울시');
-- INSERT INTO charge(CHARGE_ID,CHARGE_NAME,CHARGE_ADDR,CHARGE_TYPE,BUSI_NAME) VALUES('1006','종로구보건소','서울특별시 종로구 자하문로19길 36','2','에버온');